/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Inditrion Dradnon (https://sketchfab.com/dradnon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-holoscreen-f579a2912f8f4493a34fa0fe56abd247
Title: Laptop Holoscreen
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { useMotionValue, useSpring } from 'motion/react';

export function Laptop(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/laptop_holoscreen.glb');
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        if (animations.length > 0) {
            actions[animations[0].name]?.play();
        }
    }, [actions, animations]);

    const yPosition = useMotionValue(5);
    const ySpring = useSpring(yPosition, { damping: 30 });

    useEffect(() => {
        ySpring.set(-1);
    }, { ySpring });

    useFrame(() => {
        group.current.position.y = ySpring.get();
    })

    return (
        <group ref={group} {...props} dispose={null}
            rotation={props.rotation || [-Math.PI / 2, -0.2, 2.2]}
            scale={props.scale || 0.3}
            position={props.position || [1.3, -1, 0]}>
            <group>
                <group>
                    <group
                        position={[1.936, 11.589, -16.73]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[0.137, 0.129, 0.127]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.MaterialFBXASC032FBXASC0352142150880.geometry}
                            material={materials.MaterialFBXASC032FBXASC0352142150880}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.MaterialFBXASC032FBXASC0352142171859.geometry}
                            material={materials.MaterialFBXASC032FBXASC0352142171859}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MaterialFBXASC032FBXASC0352142172393.geometry}
                        material={materials.MaterialFBXASC032FBXASC0352142172393}
                        position={[1.936, 11.653, -18.202]}
                        rotation={[-0.262, 0, 0]}
                        scale={0.28}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/laptop_holoscreen.glb')

export default Laptop